Add terraform test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,31 @@ on:
   pull_request:
 
 jobs:
+  terraform-local:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+        - name: Set up Docker
+          uses: docker/setup-buildx-action@v3
+        - name: Install Terraform
+          uses: hashicorp/setup-terraform@v3
+          with:
+            terraform_version: 1.5.7
+        - name: Apply Terraform (local)
+          working-directory: terraform-local
+          run: |
+            terraform apply -auto-approve
+        - name: Run test against started containers
+          run: |
+            docker ps
+            curl -f http://localhost:8080/health || echo "Health check failed"
+        - name: Destroy Terraform (local)
+          if: always()
+          working-directory: terraform-local
+          run: |
+            terraform destroy -auto-approve || echo "Terraform destroy failed"
+            
   unit-test:
     name: Unit Tests
     runs-on: ubuntu-latest
